//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaloMMSiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alias
    {
        public string Player { get; set; }
        public string GT_One { get; set; }
        public string GT_Two { get; set; }
        public string GT_Three { get; set; }
        public string GT_Four { get; set; }
    }
}
