//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaloMMSiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameID
    {
        public int Id { get; set; }
        public string Player { get; set; }
        public int GameID1 { get; set; }
    }
}
